/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usjt.sistemaacademico;

import com.usjt.dao.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author erica
 */
public class CadastroUsu extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsu
     */
    public CadastroUsu() {
        initComponents();
    }

        public  void limparCampos()
            
    {
        txtNome.setText("");
        txtLogin1.setText("");
        txtSenha1.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        ckMostrarSenha = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btIncluir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        txtLogin1 = new javax.swing.JTextField();
        ckMostrarSenha1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        ckMostrarSenha.setText("Mostrar senha");
        ckMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMostrarSenhaActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btIncluir);
        btIncluir.setBounds(60, 370, 90, 22);

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(160, 370, 90, 22);

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar);
        btConsultar.setBounds(360, 370, 90, 22);

        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar);
        btAlterar.setBounds(260, 370, 90, 22);
        getContentPane().add(txtLogin1);
        txtLogin1.setBounds(60, 250, 390, 30);

        ckMostrarSenha1.setText("Mostrar senha");
        ckMostrarSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckMostrarSenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(ckMostrarSenha1);
        ckMostrarSenha1.setBounds(60, 340, 140, 20);

        jLabel4.setText("Usuário");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 230, 100, 16);

        jLabel5.setText("Senha");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 290, 150, 16);

        txtSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha1);
        txtSenha1.setBounds(60, 310, 390, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 190, 390, 30);

        jLabel6.setText("Nome");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 170, 100, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 510, 470);

        setSize(new java.awt.Dimension(531, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        String nome, login, senha;
        

        nome = txtNome.getText();
        login = txtLogin1.getText();
        senha = txtSenha1.getText();    
        
        Usuario lg = new Usuario(nome, login, senha);
  
        lg.inserir();
        limparCampos();

    }//GEN-LAST:event_btIncluirActionPerformed
    

    private void ckMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMostrarSenhaActionPerformed
        // TODO add your handling code here:
        if(ckMostrarSenha.isSelected())
        txtSenha.setEchoChar('\u0000');
        else
        txtSenha.setEchoChar('\u2022');
    }//GEN-LAST:event_ckMostrarSenhaActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void ckMostrarSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckMostrarSenha1ActionPerformed
        // TODO add your handling code here:
        if(ckMostrarSenha1.isSelected())
        txtSenha1.setEchoChar('\u0000');
        else
        txtSenha1.setEchoChar('\u2022');
    }//GEN-LAST:event_ckMostrarSenha1ActionPerformed

    private void txtSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1ActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        String login, senha;

        login = txtLogin1.getText();
        senha = txtSenha1.getText();

        Usuario lg = new Usuario(login, senha);
        lg.apagar();
        limparCampos();
        btExcluir.enable(false);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        String nome, login, senha;

        login = txtLogin1.getText();
        nome = txtNome.getText();
        
       
        Usuario lg = new Usuario();
        
        lg.Consultar(nome, login);

        txtNome.setText(lg.getNome());
        txtLogin1.setText(lg.getLogin());
        txtSenha1.setText(lg.getSenha());
        
                
        btAlterar.enable(true);
        btExcluir.enable(true);
        
        
        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        String nome, login, senha;
        

        nome = txtNome.getText();
        login = txtLogin1.getText();
        senha = txtSenha1.getText();    
        
        Usuario lg = new Usuario(nome, login, senha);
  
        lg.atualizar();
        limparCampos();
        btAlterar.enable(false);

    }//GEN-LAST:event_btAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JCheckBox ckMostrarSenha;
    private javax.swing.JCheckBox ckMostrarSenha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtLogin1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha1;
    // End of variables declaration//GEN-END:variables



}
